import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/layouts/LayoutWrapper";
import Script from "next/script";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import {
  GoogleReCaptchaProvider,
} from 'react-google-recaptcha-v3';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script src="https://translation-plugin.bhashini.co.in/v2/website_translation_utility.js" data-pos-x="5" data-pos-y="10" />
        {/* <GoogleReCaptchaProvider reCaptchaKey=""> */}
          <LayoutWrapper>{children}</LayoutWrapper>
          <ToastContainer position="top-right" autoClose={3000} />
        {/* </GoogleReCaptchaProvider> */}
      </body>
    </html>
  );
}
